[General]
Title=Основні поняття
[Question]
QuestionLine=Об'єктами стандартизації в програмній  інженерії є:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=розмір ПЗ
Variant=процеси розробки ПЗ
Variant=продукти розробки
Variant=швидкість розробки ПЗ
Variant=ресурси, які використовують процеси для створення  ПЗ
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=У реалізації великих програмних проектів  беруть участь:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=тестувальники
Variant=програмісти
Variant=менеджери
Variant=технологи
Variant=контент-менеджери
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Програмна інженерія (Software Engіneerіng) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=є галуззю комп'ютерної науки  (Computer scіence)
Variant=вивчає питання побудови комп'ютерних програм
Variant=узагальнює досвід програмування 
Variant=визначає час створення ПЗ
Variant=узагальнює правила регламентації інженерної діяльності 
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Методологія й інженерна дисципліна, що забезпечує повний цикл розробки програмної 
QuestionLine=системи називається:
QuestionLine=
QuestionLine=
Variant=структурним програмуванням
Variant=об'єктним програмуванням
Variant=програмною інженерією
Variant=CASE-технологією
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=При розробці програмного забезпечення слід ураховувати, що:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=інтелект користувача змінюється
Variant=розробка ПЗ істотно відрізняється від матеріального виробництва
Variant=економічна модель ПЗ суттєво відрізняється від звичайних 
Variant=ПЗ є "гнучким" продуктом
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Перехід від розробки програм до створення програмних продуктів і систем є:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=одним із способів підвищення ефективності програмування 
Variant=засобом прискорення програмування
Variant=засобом зниження вартості
Variant=можливістю віддаленого програмування
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=У скільки разів компонент програмного комплексу дорожче ніж окрема програма з тою 
QuestionLine=же функцією
QuestionLine=
QuestionLine=
Variant=дешевше
Variant=не дорожче
Variant=принаймні, удвічі більше
Variant=принаймні, утричі більше
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Щоб стати частиною програмного комплексу, програма повинна :
QuestionLine=
QuestionLine=
QuestionLine=
Variant=мати значний обсяг програмного коду
Variant=кожний вхід і вихід відповідає інтерфейсам
Variant=використовувати заздалегідь зазначений бюджет ресурсів
Variant=налагодження у всіх можливих комбінаціях з іншими компонентами 
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Програмний комплекс це:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=набір взаємодіючих програм, погоджених за функціями і за форматом
Variant=система вводу виводу
Variant=сімбіоз людини і машини 
Variant=єдиний засіб для розв'язку великих завдань
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Коли загострилася криза розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=60-і роки 
Variant=70-і роки 
Variant=середина 90-х років 
Variant=середина 80-х років 
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[End]
