[General]
Title=Процес розробки ПЗ
[Question]
QuestionLine=Яка властивість відсутня в структурному програмуванні 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відображення сутності предметної області
Variant=реалізація функцій верхнього рівня  
Variant=ділення програми на окремі структури
Variant=спадне програмування
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Однією з ключових вимог до розробки програмного забезпечення є те, що всі вимоги, 
QuestionLine=схеми, програмні коди й матеріали тестування повинні бути 
QuestionLine=
QuestionLine=
Variant=задокументовані
Variant=запаролені
Variant=легко доступні всім членам команди
Variant=знаходитись в онлайні
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Обрані показники якості  ПЗ повинні
QuestionLine=
QuestionLine=
QuestionLine=
Variant=впливати на кінцевий результат
Variant=заздалегідь змінюватися
Variant=обнулятися
Variant=постійно вимірюватися 
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Всі члени команди розробників
QuestionLine=
QuestionLine=
QuestionLine=
Variant=повинні дотримуватися вибраного процесу розробки
Variant=повинні мати вищу освіту
Variant=повинні мати однаковий рівень кваліфікації
Variant=повинні знаходитись в одному офісі
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Модульний підхід у процесі розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=використання ітерацій
Variant=наявність розгалужень
Variant=повний цикл розробки
Variant=повторне використання компонентів 
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Управління конфігураціями це
QuestionLine=
QuestionLine=
QuestionLine=
Variant=створення структури
Variant=ведення документації
Variant=BIOS
Variant=тестування
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Скілки ключових вимог до розробки програмного забезпечення існує 
QuestionLine=сучасній практиці розробки програмного забезпечення 
QuestionLine=
QuestionLine=
Variant=2
Variant=4
Variant=5
Variant=8
Variant=10
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Парадігма об'єктної орієнтованості заснована на:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=використанні об'єктів з даними 
Variant=використанні функціональністі
Variant=використанні платформи 4G
Variant=використанні об'єктів з об'єднанням даних і функціональністі
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Концепція Дійкстри полягала у тому, що для запису будь-якої програми в принципі 
QuestionLine=достатньо тільки трьох конструкцій управління
QuestionLine=
QuestionLine=
Variant=прямий перехід
Variant=послідовне виконання
Variant=рекурсія
Variant=цикл
Variant=розгалуження
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Чотири "П" у розробці ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=проект
Variant=персонал
Variant=продукт
Variant=перевірка
Variant=процес
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[End]
