[General]
Title=ЖИТТЄВИЙ ЦИКЛ ПЗ
[Question]
QuestionLine=Архітектура програмного забезпечення (software archіtecture) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=описує підсистеми і компоненти програмної системи
Variant=описує зв'язки між підсистемами і компонентами
Variant=визначає час роботи ПЗ
Variant=визначає внутрішню структуру системи
Variant=описує предметну область
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Список вимог до розроблювальної системи повинен включати:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=сукупність умов, при яких передбачається експлуатувати систему
Variant=опис кваліфікації розробників
Variant=опис виконуваних системою функцій
Variant=обмеження в процесі розробки 
Variant=сукупність стандартів програмування
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Процес придбання завершується в той момент, коли 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=пройшла оплата авансу
Variant=ПЗ почало працювати
Variant=в коді знайдені всі помилки 
Variant=виявилися виконаними всі умови приймання
Variant=спрацювали всі необхідні тести
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Керування конфігурацією відноситься до
QuestionLine=
QuestionLine=
QuestionLine=
Variant=основних прцесів
Variant=організвційних процесів
Variant=допоміжних процесів
Variant=непрямих процесів
Variant=процесів ітерацій
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=До основних процесів ЖЦ ПЗ відносяться
QuestionLine=
QuestionLine=
QuestionLine=
Variant=ПРОЦЕС ПРИДБАННЯ ПЗ 
Variant=ПРОЦЕСІ ПОСТАВКИ 
Variant=ПРОЦЕС ЕКСПЛУАТАЦІЇ І СУПРОВОДУ
Variant=ПРОЦЕС ІДЕНТИФІКАЦІЇ
Variant=ПРОЦЕС РОЗРОБКИ 
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Усі процеси життєвого циклу ПЗ розділені на 3 групи 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=початкові
Variant=прикінцеві
Variant=організаційні
Variant=основні
Variant=допоміжні
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Стандарт ІSO/ІEC 12207 визначає загальну структуру життєвого циклу ПЗ у вигляді 
QuestionLine=3-х східчастої моделі, яка складається із
QuestionLine=
QuestionLine=
Variant=процесів
Variant=видів діяльності 
Variant=розгалужень
Variant=завдань
Variant=циклів
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=ЖЦ ПЗ складається з:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=системний аналіз і специфікування
Variant=створення сховища даних
Variant=кодування й тестування
Variant=супроводу і припинення експлуатації
Variant=накопичення інформації
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Системний аналіз призначений для 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=для визначення контрольних точок у коді
Variant=для виявлення цілей майбутнього програмного виробу 
Variant=для з'ясування вимог до програмного виробу 
Variant=для виявлення помилок у ПЗ
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Життєвий цикл ПЗ - це період часу, який знаходиться між
QuestionLine=
QuestionLine=
QuestionLine=
Variant=ухваленням рішення про необхідність створення ПЗ
Variant=початком тестування
Variant=кодуванням
Variant=моментом його повного вилучення з експлуатації 
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Концепція життєвого циклу ПЗ (SLC - Software Lіfetіme Cycle) як послідовності кроків- 
QuestionLine=стадій,
QuestionLine=
QuestionLine=
Variant=які необхідно виконати в процесі ідентифікації ПЗ
Variant=які необхідно виконати в процесі створення програмного засобу
Variant=які необхідно виконати в процесі експлуатації ПЗ
Variant=які необхідно виконати в процесі створення БД
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Уперше про життєвий цикл заговорили 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=в 1964 році в Лондоні
Variant=в 1968 році в Лос-Анжелосі
Variant=в 1960 році в Шанхаї
Variant=в 1968 році в Лондоні
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[End]
