[General]
Title=Версії розробки ПЗ
[Question]
QuestionLine=Escrow
QuestionLine=
QuestionLine=
QuestionLine=
Variant=поділ на етапи у розробці 
Variant=RC Escrow - реліз, який готовий одержати звання релізу-кандидата
Variant=використовується завжди
Variant=перехідний місток
Variant=використовується досить рідко
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Post-release (Пост-реліз)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=завершує життєвий цикл програмного продукту
Variant=обов'язковий етап
Variant=застосовується в серйозних продуктах
Variant=до нього входить випуск відновлень безпеки або функціонала
Variant=не застосовується в серйозних продуктах
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Release (Реліз) або RTM (РТМ)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=остання версія розобки ПЗ
Variant=передається для створення майстер-копії
Variant=стабільна версія програми, що пройшла всі попередні стадії
Variant=відбувається зовнішнє тестування
Variant=випуск продукту, готового до тиражування
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Release Candіdate ( Реліз-Кандидат)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відбувається ЗБТ або ВБТ 
Variant=програми цієї стадії пройшли комплексне тестування
Variant=на цьому етапі уже є закінчений і цілісний ПП
Variant=нема ймовірність виявлення ще деякого числа помилок
Variant=існує ймовірність виявлення ще деякого числа помилок
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=На стадії Beta (Бета) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=виробник несе відповідальністіь за збитки використання бета-версі
Variant=відбувається функціональне наповнення коду
Variant=проходить публічне тестування
Variant=програми  можуть містити досить велику кількість помилок
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=На стадії Alpha (Альфа) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відбувається зовнішнє тестування
Variant=вимальовується працююча версія програмного продукту
Variant=основні особливості ПЗ вже працюють
Variant=можуть додаватися нові функціональні можливості ПЗ
Variant=імітація реальної роботи з системою штатними розроблювачами
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Pre-alpha/Concept Versіon може містити в собі
QuestionLine=
QuestionLine=
QuestionLine=
Variant=налагодження окремих модулів
Variant=тестування
Variant=власне розробку додатку
Variant=аналіз вимог
Variant=розробку дизайну
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Pre-alpha/Concept Versіon - це
QuestionLine=
QuestionLine=
QuestionLine=
Variant=початкова стадія розробки 
Variant=період часу зі старту розробки до виходу стадії Альфа
Variant=проект ПЗ
Variant=стадія, яка містить в собі весь спектр функцій ПП
Variant=стадія, яка може містити в собі не весь спектр функцій ПП
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Скільки існує версій розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=5
Variant=6
Variant=7
Variant=4
Variant=8
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Для чого використовуються стадії розробки програмного забезпечення 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=для вдосконалення процесу програмування
Variant=для прискорення  готовності програмного продукту
Variant=для опису ступеня готовності програмного продукту
Variant=для подальшої документації
Variant=для відображення кількості реалізованих функцій
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[End]
