[General]
Title=Тестування
[Question]
QuestionLine=Продукт тестують 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=в кінці розробки
Variant=після створення
Variant=на початку, в середині і в кінці
Variant=на кожному етапі ЖЦПЗ
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=На другому місці за вартістю серед етапів ЖЦ стоїть
QuestionLine=
QuestionLine=
QuestionLine=
Variant=планування
Variant=супровід
Variant=проектування
Variant=тестування
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Технічні письменники 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=пишуть технічні довідники
Variant=створюють інтерактивну довідку
Variant=дають опис технічних можливостей
Variant=розробляють "Керівництво користувача"
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Представник групи технічної підтримки
QuestionLine=
QuestionLine=
QuestionLine=
Variant=забезпечує роботу компютерів
Variant=визначає можливість віддаленої роботи
Variant=підраховує потрібні ресурси
Variant=безпосередньо контактує з користувачами
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Програміст користувацького інтерфейсу
QuestionLine=
QuestionLine=
QuestionLine=
Variant=розробляє інтерфейс програми
Variant=шукає помилки
Variant=визначає загальну внутрішню структуру коду 
Variant=організує роботу кодувальників
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Спеціаліст з аналізу людського фактору
QuestionLine=
QuestionLine=
QuestionLine=
Variant=має психологічну освіту
Variant=підбирає персонал
Variant=визначає кількість працівників
Variant=проектує програму, щоб вона була зручною і корисною
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Спеціаліст по аналізу предметної області (software analyst) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=має освіту з предметної області
Variant=повинен розуміти, чого хочуть користувачі
Variant=аналізує обсяг розробки
Variant=звязує потреби користувачів і можливості розробників
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Розроблювач архітектури (architect) визначає
QuestionLine=
QuestionLine=
QuestionLine=
Variant=кошторис ПЗ
Variant=термін виконання
Variant=чисельність персоналу
Variant=загальну внутрішню структуру коду і даних,
Variant=собівартість виконання
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Керівник проекту (project manager)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відповідає за якість ПП
Variant=відповідає своєчасне фінансування
Variant=відповідає за планування робіт
Variant=відповідає за складання бюджету розробки
Variant=відповідає трудову дисципліну
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Лабораторні випробування ПП
QuestionLine=
QuestionLine=
QuestionLine=
Variant=найчастіше виконують спеціалісти з числа майбутніх користувачів 
Variant=бета-тестування ефективніше ніж лабораторні випробування
Variant=дешевше ніж бета-тестування
Variant=виконуються в режимі "білої скриньки"
Variant=тестувальникам видаються конкретні задачі
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=На етапі супроводження ПП
QuestionLine=
QuestionLine=
QuestionLine=
Variant=значна частина коштів витрачається на пошук помилок
Variant=технологія тестування аналогічна етапу тестування
Variant=частина коштів витрачається на "білу скриньку"
Variant=найбільша частина коштів витрачається на адаптацію продукту 
Variant=витрачається біля 67% загальної вартості ПП
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Скільки етапів максимально може мати стандартна процедура тестування "чорного 
QuestionLine=ящика"?
QuestionLine=
QuestionLine=
Variant=10
Variant=24
Variant=8
Variant=19
Variant=17
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Тестування "чорного ящика"
QuestionLine=
QuestionLine=
QuestionLine=
Variant=виконується кодувальниками
Variant=виправлення однієї помилки не може привести до появи іншої
Variant=помилка приховує іншу, яка проявляється тільки після її усунення
Variant=не обов'язкове
Variant=виконується групою тестування
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Тестування на етапі тестування
QuestionLine=
QuestionLine=
QuestionLine=
Variant=тести не повторюють кожного разу, коли в програму вноситься зміни
Variant=відсутнє регресійне тестування
Variant=тестування "чорної скриньки"
Variant=тестувальник  не розглядає вихідний код програми
Variant=не виконується,якщо програма змінюється через досить тривалий час
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Переваги "білої скриньки"
QuestionLine=
QuestionLine=
QuestionLine=
Variant=Направленість тестування
Variant=Повне охоплення коду
Variant=Управління потоком
Variant=Відсутність знання внутрішньої структури
Variant=Відслідковування цілісності даних
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Тестування на етапі кодування
QuestionLine=
QuestionLine=
QuestionLine=
Variant=застосовується  технологія тестування "чорної скриньки"
Variant=застосовується  технологія тестування "білої скриньки"
Variant=тестувальник як правило не програміст 
Variant=тестувальник  розробляє тести спираючись на знанні вихідного коду
Variant=тестувальник не має  доступ до коду
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Тестування на етапі проектування
QuestionLine=
QuestionLine=
QuestionLine=
Variant=тестувальники присутні пасивно
Variant=програмна архітектура не розглядається
Variant=при аналізі проектних документів метою не є рішення проблем
Variant=тестуються тільки ідеї
Variant=зовнішній дизайн не тестується
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[End]
