[General]
Title=Види тестування
[Question]
QuestionLine=Тестування зручності використання
QuestionLine=
QuestionLine=
QuestionLine=
Variant=перевірка наскільки легко користувач системи може її освоїти
Variant=перевірка доступності документації
Variant=перевірка доступності онлайн
Variant=перевірка застрахованності системи від помилок користувача
Variant=перевірка додатку з точки зору кінцевого користувача
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Тестування стабільності або надійності
QuestionLine=
QuestionLine=
QuestionLine=
Variant=виконують зовнішні тестувальники
Variant=є необов'язковим
Variant=часто суміщають зі стрес-тестуванням
Variant=створює штучні помилки
Variant=перевірка працездатності програми при тривалому тестуванні 
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Стрес-тестування (англ. Stress Testing)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=оцінює швидкість системи в умовах перевищення нормальних меж
Variant=оцінює надійність системи в умовах перевищення нормальних меж
Variant=оцінює стійкість системи в умовах перевищення нормальних меж
Variant=оцінює надійність системи 
Variant=визначає помилки в системі в умовах перевищення нормальних меж
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Навантажувальне тестування 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=застосовується для визначення максимальної кількості користувачів
Variant=визначає вартісні показники
Variant=це тестування визначення помилок
Variant=це тестування ПП в граничних умовах експлуатації
Variant=застосовується для аналізу вимог до ресурсів
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Функціональні вимоги включають в себе:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=наявність бібліотечних функцій
Variant=функціональну придатність і точність
Variant=здатність прискорення розрахунків
Variant=здатність до взаємодії і захищеність
Variant=відповідність стандартам і правилам
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Функціональне тестування - це тестування ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=з метою перевірки здатності ПЗ вирішувати задачі користувача
Variant=з метою перевірки працездатності ПЗ
Variant=з метою перевірки інтерфейсу ПЗ
Variant=з метою перевірки реалізованості функціональних вимог
Variant=з метою перевірки швидкодії ПЗ
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=При тестуванні сірого ящика 
QuestionLine=
QuestionLine=
QuestionLine=
Variant= розробник має доступ до вихідного коду програм 
Variant= розробнику невідомі кількісні значення параметрів
Variant= розробник може писати код, який пов'язаний з бібліотеками ПЗ
Variant= розробнику відома структура об'єкта
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=При тестуванні білого ящика розробник тесту  
QuestionLine=
QuestionLine=
QuestionLine=
Variant=може писати код, який пов'язаний з бібліотеками тестованого ПЗ
Variant=має доступ до ПЗ тільки через ті ж інтерфейси, що і замовник 
Variant=тільки відома структура об'єкта
Variant=невідомі кількісні значення параметрів
Variant=має доступ до вихідного коду програм 
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=При тестуванні чорного ящика, тестувальник має доступ до ПЗ 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=до вихідного коду програм 
Variant=тільки через ті ж інтерфейси, що і замовник або користувач
Variant=через зовнішні інтерфейси
Variant=до структури об'єкта
Variant=до вихідного коду програм і структури об'єкта
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Після передачі користувачеві виконується
QuestionLine=
QuestionLine=
QuestionLine=
Variant=бета-тестування (beta testing)
Variant=приймальне тестування 
Variant=regression testing
Variant=new feature testing
Variant=тестування при здачі (acceptance or certification test)
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Тестування продуктивності (performance testing) включає
QuestionLine=
QuestionLine=
QuestionLine=
Variant=граничне тестування 
Variant=навантажувальне тестування (load testing)
Variant=початкове тестування
Variant=stress testing
Variant=тестування стабільності 
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Тестувальні "ящики" бувають таких кольорів
QuestionLine=
QuestionLine=
QuestionLine=
Variant=чорний
Variant=синій
Variant=червоний
Variant=сірий
Variant=білий
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[End]
