[General]
Title=Основні поняття
[Question]
QuestionLine=Об'єктами стандартизації в програмній  інженерії є:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=розмір ПЗ
Variant=процеси розробки ПЗ
Variant=продукти розробки
Variant=швидкість розробки ПЗ
Variant=ресурси, які використовують процеси для створення  ПЗ
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=У реалізації великих програмних проектів  беруть участь:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=тестувальники
Variant=програмісти
Variant=менеджери
Variant=технологи
Variant=контент-менеджери
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Програмна інженерія (Software Engіneerіng) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=є галуззю комп'ютерної науки  (Computer scіence)
Variant=вивчає питання побудови комп'ютерних програм
Variant=узагальнює досвід програмування 
Variant=визначає час створення ПЗ
Variant=узагальнює правила регламентації інженерної діяльності 
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Методологія й інженерна дисципліна, що забезпечує повний цикл розробки програмної 
QuestionLine=системи називається:
QuestionLine=
QuestionLine=
Variant=структурним програмуванням
Variant=об'єктним програмуванням
Variant=програмною інженерією
Variant=CASE-технологією
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=При розробці програмного забезпечення слід ураховувати, що:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=інтелект користувача змінюється
Variant=розробка ПЗ істотно відрізняється від матеріального виробництва
Variant=економічна модель ПЗ суттєво відрізняється від звичайних 
Variant=ПЗ є "гнучким" продуктом
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Перехід від розробки програм до створення програмних продуктів і систем є:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=одним із способів підвищення ефективності програмування 
Variant=засобом прискорення програмування
Variant=засобом зниження вартості
Variant=можливістю віддаленого програмування
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=У скільки разів компонент програмного комплексу дорожче ніж окрема програма з тою 
QuestionLine=же функцією
QuestionLine=
QuestionLine=
Variant=дешевше
Variant=не дорожче
Variant=принаймні, удвічі більше
Variant=принаймні, утричі більше
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Щоб стати частиною програмного комплексу, програма повинна :
QuestionLine=
QuestionLine=
QuestionLine=
Variant=мати значний обсяг програмного коду
Variant=кожний вхід і вихід відповідає інтерфейсам
Variant=використовувати заздалегідь зазначений бюджет ресурсів
Variant=налагодження у всіх можливих комбінаціях з іншими компонентами 
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Програмний комплекс це:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=набір взаємодіючих програм, погоджених за функціями і за форматом
Variant=система вводу виводу
Variant=сімбіоз людини і машини 
Variant=єдиний засіб для розв'язку великих завдань
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Коли загострилася криза розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=60-і роки 
Variant=70-і роки 
Variant=середина 90-х років 
Variant=середина 80-х років 
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
Title=Процес розробки ПЗ
[Question]
QuestionLine=Яка властивість відсутня в структурному програмуванні 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відображення сутності предметної області
Variant=реалізація функцій верхнього рівня  
Variant=ділення програми на окремі структури
Variant=спадне програмування
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Однією з ключових вимог до розробки програмного забезпечення є те, що всі вимоги, 
QuestionLine=схеми, програмні коди й матеріали тестування повинні бути 
QuestionLine=
QuestionLine=
Variant=задокументовані
Variant=запаролені
Variant=легко доступні всім членам команди
Variant=знаходитись в онлайні
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Обрані показники якості  ПЗ повинні
QuestionLine=
QuestionLine=
QuestionLine=
Variant=впливати на кінцевий результат
Variant=заздалегідь змінюватися
Variant=обнулятися
Variant=постійно вимірюватися 
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Всі члени команди розробників
QuestionLine=
QuestionLine=
QuestionLine=
Variant=повинні дотримуватися вибраного процесу розробки
Variant=повинні мати вищу освіту
Variant=повинні мати однаковий рівень кваліфікації
Variant=повинні знаходитись в одному офісі
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Модульний підхід у процесі розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=використання ітерацій
Variant=наявність розгалужень
Variant=повний цикл розробки
Variant=повторне використання компонентів 
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Управління конфігураціями це
QuestionLine=
QuestionLine=
QuestionLine=
Variant=створення структури
Variant=ведення документації
Variant=BIOS
Variant=тестування
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Скілки ключових вимог до розробки програмного забезпечення існує 
QuestionLine=сучасній практиці розробки програмного забезпечення 
QuestionLine=
QuestionLine=
Variant=2
Variant=4
Variant=5
Variant=8
Variant=10
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Парадігма об'єктної орієнтованості заснована на:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=використанні об'єктів з даними 
Variant=використанні функціональністі
Variant=використанні платформи 4G
Variant=використанні об'єктів з об'єднанням даних і функціональністі
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Концепція Дійкстри полягала у тому, що для запису будь-якої програми в принципі 
QuestionLine=достатньо тільки трьох конструкцій управління
QuestionLine=
QuestionLine=
Variant=прямий перехід
Variant=послідовне виконання
Variant=рекурсія
Variant=цикл
Variant=розгалуження
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Чотири "П" у розробці ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=проект
Variant=персонал
Variant=продукт
Variant=перевірка
Variant=процес
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
Title=ЖИТТЄВИЙ ЦИКЛ ПЗ
[Question]
QuestionLine=Архітектура програмного забезпечення (software archіtecture) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=описує підсистеми і компоненти програмної системи
Variant=описує зв'язки між підсистемами і компонентами
Variant=визначає час роботи ПЗ
Variant=визначає внутрішню структуру системи
Variant=описує предметну область
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Список вимог до розроблювальної системи повинен включати:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=сукупність умов, при яких передбачається експлуатувати систему
Variant=опис кваліфікації розробників
Variant=опис виконуваних системою функцій
Variant=обмеження в процесі розробки 
Variant=сукупність стандартів програмування
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Процес придбання завершується в той момент, коли 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=пройшла оплата авансу
Variant=ПЗ почало працювати
Variant=в коді знайдені всі помилки 
Variant=виявилися виконаними всі умови приймання
Variant=спрацювали всі необхідні тести
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Керування конфігурацією відноситься до
QuestionLine=
QuestionLine=
QuestionLine=
Variant=основних прцесів
Variant=організвційних процесів
Variant=допоміжних процесів
Variant=непрямих процесів
Variant=процесів ітерацій
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=До основних процесів ЖЦ ПЗ відносяться
QuestionLine=
QuestionLine=
QuestionLine=
Variant=ПРОЦЕС ПРИДБАННЯ ПЗ 
Variant=ПРОЦЕСІ ПОСТАВКИ 
Variant=ПРОЦЕС ЕКСПЛУАТАЦІЇ І СУПРОВОДУ
Variant=ПРОЦЕС ІДЕНТИФІКАЦІЇ
Variant=ПРОЦЕС РОЗРОБКИ 
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Усі процеси життєвого циклу ПЗ розділені на 3 групи 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=початкові
Variant=прикінцеві
Variant=організаційні
Variant=основні
Variant=допоміжні
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Стандарт ІSO/ІEC 12207 визначає загальну структуру життєвого циклу ПЗ у вигляді 
QuestionLine=3-х східчастої моделі, яка складається із
QuestionLine=
QuestionLine=
Variant=процесів
Variant=видів діяльності 
Variant=розгалужень
Variant=завдань
Variant=циклів
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=ЖЦ ПЗ складається з:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=системний аналіз і специфікування
Variant=створення сховища даних
Variant=кодування й тестування
Variant=супроводу і припинення експлуатації
Variant=накопичення інформації
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Системний аналіз призначений для 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=для визначення контрольних точок у коді
Variant=для виявлення цілей майбутнього програмного виробу 
Variant=для з'ясування вимог до програмного виробу 
Variant=для виявлення помилок у ПЗ
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Життєвий цикл ПЗ - це період часу, який знаходиться між
QuestionLine=
QuestionLine=
QuestionLine=
Variant=ухваленням рішення про необхідність створення ПЗ
Variant=початком тестування
Variant=кодуванням
Variant=моментом його повного вилучення з експлуатації 
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Концепція життєвого циклу ПЗ (SLC - Software Lіfetіme Cycle) як послідовності кроків- 
QuestionLine=стадій,
QuestionLine=
QuestionLine=
Variant=які необхідно виконати в процесі ідентифікації ПЗ
Variant=які необхідно виконати в процесі створення програмного засобу
Variant=які необхідно виконати в процесі експлуатації ПЗ
Variant=які необхідно виконати в процесі створення БД
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Уперше про життєвий цикл заговорили 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=в 1964 році в Лондоні
Variant=в 1968 році в Лос-Анжелосі
Variant=в 1960 році в Шанхаї
Variant=в 1968 році в Лондоні
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Основна складність при реалізації спіральної моделі
QuestionLine=
QuestionLine=
QuestionLine=
Variant=підтримка цілісності документації
Variant=велика кількість ітерацій
Variant=необхідність попередження ризиків
Variant=необхідність надати замовнику часткову версію 
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Модель називється інкрементальною з точки зору
QuestionLine=
QuestionLine=
QuestionLine=
Variant=структури життєвого циклу 
Variant=розвитку продукту 
Variant=системного аналітика
Variant=тестувальника
Variant=
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Які процеси називаються ітеративними?
QuestionLine=
QuestionLine=
QuestionLine=
Variant=які повторюються
Variant=початкові
Variant=кінцеві
Variant=в яких водоспадна модель використовується багаторазово
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Водоспадну модель розширюють наступними додатковими фазами:
QuestionLine=
QuestionLine=
QuestionLine=
Variant=ОО аналіз
Variant=модульне і системне тестування
Variant=системний аналіз
Variant=супровід
Variant=концептуальний аналіз
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Основний недолік каскадного підходу
QuestionLine=
QuestionLine=
QuestionLine=
Variant=декомпозиція задачі
Variant=потреба в поверненні до попередніх етапів
Variant=перегляд раніше ухвалених рішень
Variant=істотне запізнювання з одержанням результатів
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Водоспадна модель складається з 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=аналізу і проектування
Variant=реалізації та інтеграції
Variant=композиції
Variant=узагальнення
Variant=тестування
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Водоспадна модель була запропонована 
QuestionLine=
QuestionLine=
QuestionLine=
Variant= в 1970 році 
Variant=в 1975 році
Variant=Дійкстрою
Variant=Вінстоном Ройсом
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=У рамках однієї фази може виконуватися різних видів діяльності
QuestionLine=
QuestionLine=
QuestionLine=
Variant=багато
Variant=не більше 1-ї
Variant=не менше 3-х
Variant=не вионуватися взагалі
Variant=
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Вид діяльності (actіvіty)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=професія
Variant=спрямування 
Variant=певний тип роботи, виконуваний у процесі розробки ПЗ
Variant=учбове навантаження
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Фаза (phase)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=це певний етап процесу, що має вихідний результ
Variant=завершує життєвий цикл програмного продукту
Variant=починає життєвий цикл програмного продукту
Variant=це певний етап процесу, що має початок, кінець і вихідний результ
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Escrow
QuestionLine=
QuestionLine=
QuestionLine=
Variant=поділ на етапи у розробці 
Variant=RC Escrow - реліз, який готовий одержати звання релізу-кандидата
Variant=використовується завжди
Variant=перехідний місток
Variant=використовується досить рідко
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Post-release (Пост-реліз)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=завершує життєвий цикл програмного продукту
Variant=обов'язковий етап
Variant=застосовується в серйозних продуктах
Variant=до нього входить випуск відновлень безпеки або функціонала
Variant=не застосовується в серйозних продуктах
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=Release (Реліз) або RTM (РТМ)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=остання версія розобки ПЗ
Variant=передається для створення майстер-копії
Variant=стабільна версія програми, що пройшла всі попередні стадії
Variant=відбувається зовнішнє тестування
Variant=випуск продукту, готового до тиражування
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Release Candіdate ( Реліз-Кандидат)
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відбувається ЗБТ або ВБТ 
Variant=програми цієї стадії пройшли комплексне тестування
Variant=на цьому етапі уже є закінчений і цілісний ПП
Variant=нема ймовірність виявлення ще деякого числа помилок
Variant=існує ймовірність виявлення ще деякого числа помилок
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=На стадії Beta (Бета) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=виробник несе відповідальністіь за збитки використання бета-версі
Variant=відбувається функціональне наповнення коду
Variant=проходить публічне тестування
Variant=програми  можуть містити досить велику кількість помилок
Variant=
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
[Question]
QuestionLine=На стадії Alpha (Альфа) 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=відбувається зовнішнє тестування
Variant=вимальовується працююча версія програмного продукту
Variant=основні особливості ПЗ вже працюють
Variant=можуть додаватися нові функціональні можливості ПЗ
Variant=імітація реальної роботи з системою штатними розроблювачами
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Pre-alpha/Concept Versіon може містити в собі
QuestionLine=
QuestionLine=
QuestionLine=
Variant=налагодження окремих модулів
Variant=тестування
Variant=власне розробку додатку
Variant=аналіз вимог
Variant=розробку дизайну
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
CorrectVariant=1
CorrectVariant=1
[Question]
QuestionLine=Pre-alpha/Concept Versіon - це
QuestionLine=
QuestionLine=
QuestionLine=
Variant=початкова стадія розробки 
Variant=період часу зі старту розробки до виходу стадії Альфа
Variant=проект ПЗ
Variant=стадія, яка містить в собі весь спектр функцій ПП
Variant=стадія, яка може містити в собі не весь спектр функцій ПП
CorrectVariant=1
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
[Question]
QuestionLine=Скільки існує версій розробки ПЗ
QuestionLine=
QuestionLine=
QuestionLine=
Variant=5
Variant=6
Variant=7
Variant=4
Variant=8
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=0
CorrectVariant=0
[Question]
QuestionLine=Для чого використовуються стадії розробки програмного забезпечення 
QuestionLine=
QuestionLine=
QuestionLine=
Variant=для вдосконалення процесу програмування
Variant=для прискорення  готовності програмного продукту
Variant=для опису ступеня готовності програмного продукту
Variant=для подальшої документації
Variant=для відображення кількості реалізованих функцій
CorrectVariant=0
CorrectVariant=0
CorrectVariant=1
CorrectVariant=0
CorrectVariant=1
[End]
